[versions]
# 플러그인
agp = "8.4.1"
kotlin = "1.9.24"
ksp = "1.9.24-1.0.20"
aboutlib = "11.2.1"


# 라이브러리
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"

coreKtx = "1.13.1"
appcompat = "1.7.0"
constraintlayout = "2.1.4"
swipeRefreshLayout = "1.1.0"

material = "1.12.0"

hilt = "2.51.1"
hiltX = "1.2.0"

glide = "4.16.0"
retrofit = "2.11.0"
themedToggleButton = "1.4.1"
youtubePlayer = "12.1.0"
calendar = "2.5.1"
readmore = "1.0.0"

desugar_jdk_libs = "2.0.4"


[libraries]
# 테스트
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

# androidx
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-swipeRefreshLayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swipeRefreshLayout" }

# google
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-navigation = { group = "androidx.hilt", name = "hilt-navigation-fragment", version.ref = "hiltX" }

# 기타
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
themedToggleButton = { group = "nl.bryanderidder", name = "themed-toggle-button-group", version.ref = "themedToggleButton" }
youtubePlayer = { group = "com.pierfrancescosoffritti.androidyoutubeplayer", name = "core", version.ref = "youtubePlayer" }
calendar = { group = "com.kizitonwose.calendar", name = "view", version.ref = "calendar" }
readmore = { group = "kr.co.prnd", name = "readmore-textview", version.ref = "readmore" }
aboutlibraries = { group = "com.mikepenz", name = "aboutlibraries", version.ref = "aboutlib" }

desugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugar_jdk_libs" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
aboutlib = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutlib" }